<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fcseminars"
 *
 * Auto generated by Extension Builder 2015-05-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'fcseminars',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Michael Beckhöfer',
	'author_email' => 'michael.beckhoefer@f-com.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => 'tx_seminars_seminars',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'seminars' => '0.9.99-0.10.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
